spring:
  application:
    name: shopping-account
  profiles:
    include: core,service
    active: dev
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
stiger:
  shopping:
    token:
      exclude-paths:
        - pattern: /auth/token
          method: post
        - pattern: /account
          method: post