FROM mysql:5.7.29
MAINTAINER snake19870227
VOLUME ["/tmp"]
COPY ./my.cnf /etc/mysql/conf.d
COPY ./init.sql /docker-entrypoint-initdb.d
RUN ln -snf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime \
    && echo Asia/Shanghai > /etc/timezone